//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.6.4
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from E:\workspaceCS\AntlrDLL\AntlrDLL\AntlrDLL\Protobuf3.g4 by ANTLR 4.6.4

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace AntlrDLL {

using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IProtobuf3Listener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.6.4")]
[System.CLSCompliant(false)]
public partial class Protobuf3BaseListener : IProtobuf3Listener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="Protobuf3Parser.proto"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProto([NotNull] Protobuf3Parser.ProtoContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Protobuf3Parser.proto"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProto([NotNull] Protobuf3Parser.ProtoContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="Protobuf3Parser.syntax"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSyntax([NotNull] Protobuf3Parser.SyntaxContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Protobuf3Parser.syntax"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSyntax([NotNull] Protobuf3Parser.SyntaxContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="Protobuf3Parser.importStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterImportStatement([NotNull] Protobuf3Parser.ImportStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Protobuf3Parser.importStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitImportStatement([NotNull] Protobuf3Parser.ImportStatementContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="Protobuf3Parser.packageStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPackageStatement([NotNull] Protobuf3Parser.PackageStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Protobuf3Parser.packageStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPackageStatement([NotNull] Protobuf3Parser.PackageStatementContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="Protobuf3Parser.option"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOption([NotNull] Protobuf3Parser.OptionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Protobuf3Parser.option"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOption([NotNull] Protobuf3Parser.OptionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="Protobuf3Parser.optionName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOptionName([NotNull] Protobuf3Parser.OptionNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Protobuf3Parser.optionName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOptionName([NotNull] Protobuf3Parser.OptionNameContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="Protobuf3Parser.topLevelDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTopLevelDef([NotNull] Protobuf3Parser.TopLevelDefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Protobuf3Parser.topLevelDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTopLevelDef([NotNull] Protobuf3Parser.TopLevelDefContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="Protobuf3Parser.message"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMessage([NotNull] Protobuf3Parser.MessageContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Protobuf3Parser.message"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMessage([NotNull] Protobuf3Parser.MessageContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="Protobuf3Parser.messageBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMessageBody([NotNull] Protobuf3Parser.MessageBodyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Protobuf3Parser.messageBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMessageBody([NotNull] Protobuf3Parser.MessageBodyContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="Protobuf3Parser.enumDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEnumDefinition([NotNull] Protobuf3Parser.EnumDefinitionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Protobuf3Parser.enumDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEnumDefinition([NotNull] Protobuf3Parser.EnumDefinitionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="Protobuf3Parser.enumBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEnumBody([NotNull] Protobuf3Parser.EnumBodyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Protobuf3Parser.enumBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEnumBody([NotNull] Protobuf3Parser.EnumBodyContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="Protobuf3Parser.enumField"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEnumField([NotNull] Protobuf3Parser.EnumFieldContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Protobuf3Parser.enumField"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEnumField([NotNull] Protobuf3Parser.EnumFieldContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="Protobuf3Parser.enumValueOption"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEnumValueOption([NotNull] Protobuf3Parser.EnumValueOptionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Protobuf3Parser.enumValueOption"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEnumValueOption([NotNull] Protobuf3Parser.EnumValueOptionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="Protobuf3Parser.service"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterService([NotNull] Protobuf3Parser.ServiceContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Protobuf3Parser.service"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitService([NotNull] Protobuf3Parser.ServiceContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="Protobuf3Parser.rpc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRpc([NotNull] Protobuf3Parser.RpcContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Protobuf3Parser.rpc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRpc([NotNull] Protobuf3Parser.RpcContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="Protobuf3Parser.reserved"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterReserved([NotNull] Protobuf3Parser.ReservedContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Protobuf3Parser.reserved"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitReserved([NotNull] Protobuf3Parser.ReservedContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="Protobuf3Parser.ranges"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRanges([NotNull] Protobuf3Parser.RangesContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Protobuf3Parser.ranges"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRanges([NotNull] Protobuf3Parser.RangesContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="Protobuf3Parser.range"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRange([NotNull] Protobuf3Parser.RangeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Protobuf3Parser.range"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRange([NotNull] Protobuf3Parser.RangeContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="Protobuf3Parser.fieldNames"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFieldNames([NotNull] Protobuf3Parser.FieldNamesContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Protobuf3Parser.fieldNames"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFieldNames([NotNull] Protobuf3Parser.FieldNamesContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="Protobuf3Parser.type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterType([NotNull] Protobuf3Parser.TypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Protobuf3Parser.type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitType([NotNull] Protobuf3Parser.TypeContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="Protobuf3Parser.fieldNumber"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFieldNumber([NotNull] Protobuf3Parser.FieldNumberContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Protobuf3Parser.fieldNumber"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFieldNumber([NotNull] Protobuf3Parser.FieldNumberContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="Protobuf3Parser.field"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterField([NotNull] Protobuf3Parser.FieldContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Protobuf3Parser.field"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitField([NotNull] Protobuf3Parser.FieldContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="Protobuf3Parser.fieldOptions"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFieldOptions([NotNull] Protobuf3Parser.FieldOptionsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Protobuf3Parser.fieldOptions"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFieldOptions([NotNull] Protobuf3Parser.FieldOptionsContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="Protobuf3Parser.fieldOption"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFieldOption([NotNull] Protobuf3Parser.FieldOptionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Protobuf3Parser.fieldOption"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFieldOption([NotNull] Protobuf3Parser.FieldOptionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="Protobuf3Parser.oneof"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOneof([NotNull] Protobuf3Parser.OneofContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Protobuf3Parser.oneof"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOneof([NotNull] Protobuf3Parser.OneofContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="Protobuf3Parser.oneofField"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOneofField([NotNull] Protobuf3Parser.OneofFieldContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Protobuf3Parser.oneofField"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOneofField([NotNull] Protobuf3Parser.OneofFieldContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="Protobuf3Parser.mapField"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMapField([NotNull] Protobuf3Parser.MapFieldContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Protobuf3Parser.mapField"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMapField([NotNull] Protobuf3Parser.MapFieldContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="Protobuf3Parser.keyType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterKeyType([NotNull] Protobuf3Parser.KeyTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Protobuf3Parser.keyType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitKeyType([NotNull] Protobuf3Parser.KeyTypeContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="Protobuf3Parser.fullIdent"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFullIdent([NotNull] Protobuf3Parser.FullIdentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Protobuf3Parser.fullIdent"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFullIdent([NotNull] Protobuf3Parser.FullIdentContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="Protobuf3Parser.messageName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMessageName([NotNull] Protobuf3Parser.MessageNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Protobuf3Parser.messageName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMessageName([NotNull] Protobuf3Parser.MessageNameContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="Protobuf3Parser.enumName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEnumName([NotNull] Protobuf3Parser.EnumNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Protobuf3Parser.enumName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEnumName([NotNull] Protobuf3Parser.EnumNameContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="Protobuf3Parser.messageOrEnumName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMessageOrEnumName([NotNull] Protobuf3Parser.MessageOrEnumNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Protobuf3Parser.messageOrEnumName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMessageOrEnumName([NotNull] Protobuf3Parser.MessageOrEnumNameContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="Protobuf3Parser.fieldName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFieldName([NotNull] Protobuf3Parser.FieldNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Protobuf3Parser.fieldName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFieldName([NotNull] Protobuf3Parser.FieldNameContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="Protobuf3Parser.oneofName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOneofName([NotNull] Protobuf3Parser.OneofNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Protobuf3Parser.oneofName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOneofName([NotNull] Protobuf3Parser.OneofNameContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="Protobuf3Parser.mapName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMapName([NotNull] Protobuf3Parser.MapNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Protobuf3Parser.mapName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMapName([NotNull] Protobuf3Parser.MapNameContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="Protobuf3Parser.serviceName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterServiceName([NotNull] Protobuf3Parser.ServiceNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Protobuf3Parser.serviceName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitServiceName([NotNull] Protobuf3Parser.ServiceNameContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="Protobuf3Parser.rpcName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRpcName([NotNull] Protobuf3Parser.RpcNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Protobuf3Parser.rpcName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRpcName([NotNull] Protobuf3Parser.RpcNameContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="Protobuf3Parser.messageType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMessageType([NotNull] Protobuf3Parser.MessageTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Protobuf3Parser.messageType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMessageType([NotNull] Protobuf3Parser.MessageTypeContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="Protobuf3Parser.messageOrEnumType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMessageOrEnumType([NotNull] Protobuf3Parser.MessageOrEnumTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Protobuf3Parser.messageOrEnumType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMessageOrEnumType([NotNull] Protobuf3Parser.MessageOrEnumTypeContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="Protobuf3Parser.emptyStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEmptyStatement([NotNull] Protobuf3Parser.EmptyStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Protobuf3Parser.emptyStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEmptyStatement([NotNull] Protobuf3Parser.EmptyStatementContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="Protobuf3Parser.constant"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConstant([NotNull] Protobuf3Parser.ConstantContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Protobuf3Parser.constant"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConstant([NotNull] Protobuf3Parser.ConstantContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
} // namespace AntlrDLL
