//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.6.4
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from E:\workspaceCS\AntlrDLL\AntlrDLL\AntlrDLL\Protobuf3.g4 by ANTLR 4.6.4

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace AntlrDLL {
using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="Protobuf3Parser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.6.4")]
[System.CLSCompliant(false)]
public interface IProtobuf3Listener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="Protobuf3Parser.proto"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProto([NotNull] Protobuf3Parser.ProtoContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Protobuf3Parser.proto"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProto([NotNull] Protobuf3Parser.ProtoContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="Protobuf3Parser.syntax"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSyntax([NotNull] Protobuf3Parser.SyntaxContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Protobuf3Parser.syntax"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSyntax([NotNull] Protobuf3Parser.SyntaxContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="Protobuf3Parser.importStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterImportStatement([NotNull] Protobuf3Parser.ImportStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Protobuf3Parser.importStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitImportStatement([NotNull] Protobuf3Parser.ImportStatementContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="Protobuf3Parser.packageStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPackageStatement([NotNull] Protobuf3Parser.PackageStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Protobuf3Parser.packageStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPackageStatement([NotNull] Protobuf3Parser.PackageStatementContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="Protobuf3Parser.option"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOption([NotNull] Protobuf3Parser.OptionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Protobuf3Parser.option"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOption([NotNull] Protobuf3Parser.OptionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="Protobuf3Parser.optionName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOptionName([NotNull] Protobuf3Parser.OptionNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Protobuf3Parser.optionName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOptionName([NotNull] Protobuf3Parser.OptionNameContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="Protobuf3Parser.topLevelDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTopLevelDef([NotNull] Protobuf3Parser.TopLevelDefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Protobuf3Parser.topLevelDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTopLevelDef([NotNull] Protobuf3Parser.TopLevelDefContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="Protobuf3Parser.message"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMessage([NotNull] Protobuf3Parser.MessageContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Protobuf3Parser.message"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMessage([NotNull] Protobuf3Parser.MessageContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="Protobuf3Parser.messageBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMessageBody([NotNull] Protobuf3Parser.MessageBodyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Protobuf3Parser.messageBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMessageBody([NotNull] Protobuf3Parser.MessageBodyContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="Protobuf3Parser.enumDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEnumDefinition([NotNull] Protobuf3Parser.EnumDefinitionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Protobuf3Parser.enumDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEnumDefinition([NotNull] Protobuf3Parser.EnumDefinitionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="Protobuf3Parser.enumBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEnumBody([NotNull] Protobuf3Parser.EnumBodyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Protobuf3Parser.enumBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEnumBody([NotNull] Protobuf3Parser.EnumBodyContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="Protobuf3Parser.enumField"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEnumField([NotNull] Protobuf3Parser.EnumFieldContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Protobuf3Parser.enumField"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEnumField([NotNull] Protobuf3Parser.EnumFieldContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="Protobuf3Parser.enumValueOption"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEnumValueOption([NotNull] Protobuf3Parser.EnumValueOptionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Protobuf3Parser.enumValueOption"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEnumValueOption([NotNull] Protobuf3Parser.EnumValueOptionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="Protobuf3Parser.service"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterService([NotNull] Protobuf3Parser.ServiceContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Protobuf3Parser.service"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitService([NotNull] Protobuf3Parser.ServiceContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="Protobuf3Parser.rpc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRpc([NotNull] Protobuf3Parser.RpcContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Protobuf3Parser.rpc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRpc([NotNull] Protobuf3Parser.RpcContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="Protobuf3Parser.reserved"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReserved([NotNull] Protobuf3Parser.ReservedContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Protobuf3Parser.reserved"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReserved([NotNull] Protobuf3Parser.ReservedContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="Protobuf3Parser.ranges"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRanges([NotNull] Protobuf3Parser.RangesContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Protobuf3Parser.ranges"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRanges([NotNull] Protobuf3Parser.RangesContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="Protobuf3Parser.range"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRange([NotNull] Protobuf3Parser.RangeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Protobuf3Parser.range"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRange([NotNull] Protobuf3Parser.RangeContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="Protobuf3Parser.fieldNames"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFieldNames([NotNull] Protobuf3Parser.FieldNamesContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Protobuf3Parser.fieldNames"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFieldNames([NotNull] Protobuf3Parser.FieldNamesContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="Protobuf3Parser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterType([NotNull] Protobuf3Parser.TypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Protobuf3Parser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitType([NotNull] Protobuf3Parser.TypeContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="Protobuf3Parser.fieldNumber"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFieldNumber([NotNull] Protobuf3Parser.FieldNumberContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Protobuf3Parser.fieldNumber"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFieldNumber([NotNull] Protobuf3Parser.FieldNumberContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="Protobuf3Parser.field"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterField([NotNull] Protobuf3Parser.FieldContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Protobuf3Parser.field"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitField([NotNull] Protobuf3Parser.FieldContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="Protobuf3Parser.fieldOptions"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFieldOptions([NotNull] Protobuf3Parser.FieldOptionsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Protobuf3Parser.fieldOptions"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFieldOptions([NotNull] Protobuf3Parser.FieldOptionsContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="Protobuf3Parser.fieldOption"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFieldOption([NotNull] Protobuf3Parser.FieldOptionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Protobuf3Parser.fieldOption"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFieldOption([NotNull] Protobuf3Parser.FieldOptionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="Protobuf3Parser.oneof"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOneof([NotNull] Protobuf3Parser.OneofContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Protobuf3Parser.oneof"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOneof([NotNull] Protobuf3Parser.OneofContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="Protobuf3Parser.oneofField"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOneofField([NotNull] Protobuf3Parser.OneofFieldContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Protobuf3Parser.oneofField"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOneofField([NotNull] Protobuf3Parser.OneofFieldContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="Protobuf3Parser.mapField"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMapField([NotNull] Protobuf3Parser.MapFieldContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Protobuf3Parser.mapField"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMapField([NotNull] Protobuf3Parser.MapFieldContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="Protobuf3Parser.keyType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterKeyType([NotNull] Protobuf3Parser.KeyTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Protobuf3Parser.keyType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitKeyType([NotNull] Protobuf3Parser.KeyTypeContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="Protobuf3Parser.fullIdent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFullIdent([NotNull] Protobuf3Parser.FullIdentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Protobuf3Parser.fullIdent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFullIdent([NotNull] Protobuf3Parser.FullIdentContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="Protobuf3Parser.messageName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMessageName([NotNull] Protobuf3Parser.MessageNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Protobuf3Parser.messageName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMessageName([NotNull] Protobuf3Parser.MessageNameContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="Protobuf3Parser.enumName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEnumName([NotNull] Protobuf3Parser.EnumNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Protobuf3Parser.enumName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEnumName([NotNull] Protobuf3Parser.EnumNameContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="Protobuf3Parser.messageOrEnumName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMessageOrEnumName([NotNull] Protobuf3Parser.MessageOrEnumNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Protobuf3Parser.messageOrEnumName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMessageOrEnumName([NotNull] Protobuf3Parser.MessageOrEnumNameContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="Protobuf3Parser.fieldName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFieldName([NotNull] Protobuf3Parser.FieldNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Protobuf3Parser.fieldName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFieldName([NotNull] Protobuf3Parser.FieldNameContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="Protobuf3Parser.oneofName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOneofName([NotNull] Protobuf3Parser.OneofNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Protobuf3Parser.oneofName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOneofName([NotNull] Protobuf3Parser.OneofNameContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="Protobuf3Parser.mapName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMapName([NotNull] Protobuf3Parser.MapNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Protobuf3Parser.mapName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMapName([NotNull] Protobuf3Parser.MapNameContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="Protobuf3Parser.serviceName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterServiceName([NotNull] Protobuf3Parser.ServiceNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Protobuf3Parser.serviceName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitServiceName([NotNull] Protobuf3Parser.ServiceNameContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="Protobuf3Parser.rpcName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRpcName([NotNull] Protobuf3Parser.RpcNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Protobuf3Parser.rpcName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRpcName([NotNull] Protobuf3Parser.RpcNameContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="Protobuf3Parser.messageType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMessageType([NotNull] Protobuf3Parser.MessageTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Protobuf3Parser.messageType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMessageType([NotNull] Protobuf3Parser.MessageTypeContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="Protobuf3Parser.messageOrEnumType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMessageOrEnumType([NotNull] Protobuf3Parser.MessageOrEnumTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Protobuf3Parser.messageOrEnumType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMessageOrEnumType([NotNull] Protobuf3Parser.MessageOrEnumTypeContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="Protobuf3Parser.emptyStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEmptyStatement([NotNull] Protobuf3Parser.EmptyStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Protobuf3Parser.emptyStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEmptyStatement([NotNull] Protobuf3Parser.EmptyStatementContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="Protobuf3Parser.constant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConstant([NotNull] Protobuf3Parser.ConstantContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Protobuf3Parser.constant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConstant([NotNull] Protobuf3Parser.ConstantContext context);
}
} // namespace AntlrDLL
