//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.6.4
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from E:\workspaceCS\AntlrDLL\AntlrDLL\AntlrDLL\Protobuf3.g4 by ANTLR 4.6.4

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace AntlrDLL {
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="Protobuf3Parser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.6.4")]
[System.CLSCompliant(false)]
public interface IProtobuf3Visitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="Protobuf3Parser.proto"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProto([NotNull] Protobuf3Parser.ProtoContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="Protobuf3Parser.syntax"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSyntax([NotNull] Protobuf3Parser.SyntaxContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="Protobuf3Parser.importStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitImportStatement([NotNull] Protobuf3Parser.ImportStatementContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="Protobuf3Parser.packageStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPackageStatement([NotNull] Protobuf3Parser.PackageStatementContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="Protobuf3Parser.option"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOption([NotNull] Protobuf3Parser.OptionContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="Protobuf3Parser.optionName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOptionName([NotNull] Protobuf3Parser.OptionNameContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="Protobuf3Parser.topLevelDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTopLevelDef([NotNull] Protobuf3Parser.TopLevelDefContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="Protobuf3Parser.message"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMessage([NotNull] Protobuf3Parser.MessageContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="Protobuf3Parser.messageBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMessageBody([NotNull] Protobuf3Parser.MessageBodyContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="Protobuf3Parser.enumDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumDefinition([NotNull] Protobuf3Parser.EnumDefinitionContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="Protobuf3Parser.enumBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumBody([NotNull] Protobuf3Parser.EnumBodyContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="Protobuf3Parser.enumField"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumField([NotNull] Protobuf3Parser.EnumFieldContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="Protobuf3Parser.enumValueOption"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumValueOption([NotNull] Protobuf3Parser.EnumValueOptionContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="Protobuf3Parser.service"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitService([NotNull] Protobuf3Parser.ServiceContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="Protobuf3Parser.rpc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRpc([NotNull] Protobuf3Parser.RpcContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="Protobuf3Parser.reserved"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReserved([NotNull] Protobuf3Parser.ReservedContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="Protobuf3Parser.ranges"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRanges([NotNull] Protobuf3Parser.RangesContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="Protobuf3Parser.range"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRange([NotNull] Protobuf3Parser.RangeContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="Protobuf3Parser.fieldNames"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFieldNames([NotNull] Protobuf3Parser.FieldNamesContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="Protobuf3Parser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType([NotNull] Protobuf3Parser.TypeContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="Protobuf3Parser.fieldNumber"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFieldNumber([NotNull] Protobuf3Parser.FieldNumberContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="Protobuf3Parser.field"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitField([NotNull] Protobuf3Parser.FieldContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="Protobuf3Parser.fieldOptions"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFieldOptions([NotNull] Protobuf3Parser.FieldOptionsContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="Protobuf3Parser.fieldOption"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFieldOption([NotNull] Protobuf3Parser.FieldOptionContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="Protobuf3Parser.oneof"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOneof([NotNull] Protobuf3Parser.OneofContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="Protobuf3Parser.oneofField"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOneofField([NotNull] Protobuf3Parser.OneofFieldContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="Protobuf3Parser.mapField"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMapField([NotNull] Protobuf3Parser.MapFieldContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="Protobuf3Parser.keyType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitKeyType([NotNull] Protobuf3Parser.KeyTypeContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="Protobuf3Parser.fullIdent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFullIdent([NotNull] Protobuf3Parser.FullIdentContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="Protobuf3Parser.messageName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMessageName([NotNull] Protobuf3Parser.MessageNameContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="Protobuf3Parser.enumName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumName([NotNull] Protobuf3Parser.EnumNameContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="Protobuf3Parser.messageOrEnumName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMessageOrEnumName([NotNull] Protobuf3Parser.MessageOrEnumNameContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="Protobuf3Parser.fieldName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFieldName([NotNull] Protobuf3Parser.FieldNameContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="Protobuf3Parser.oneofName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOneofName([NotNull] Protobuf3Parser.OneofNameContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="Protobuf3Parser.mapName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMapName([NotNull] Protobuf3Parser.MapNameContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="Protobuf3Parser.serviceName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitServiceName([NotNull] Protobuf3Parser.ServiceNameContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="Protobuf3Parser.rpcName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRpcName([NotNull] Protobuf3Parser.RpcNameContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="Protobuf3Parser.messageType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMessageType([NotNull] Protobuf3Parser.MessageTypeContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="Protobuf3Parser.messageOrEnumType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMessageOrEnumType([NotNull] Protobuf3Parser.MessageOrEnumTypeContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="Protobuf3Parser.emptyStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEmptyStatement([NotNull] Protobuf3Parser.EmptyStatementContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="Protobuf3Parser.constant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConstant([NotNull] Protobuf3Parser.ConstantContext context);
}
} // namespace AntlrDLL
